services:
  wordpress:
    build:
      context: .
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./logs:/var/log/php
      - ./wp-content:/var/www/html/wp-content
    environment:
      - WORDPRESS_DB_HOST=mysql:3306
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_DEBUG=1
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:8.3.0
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
      - MYSQL_DATABASE=wordpress
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "mysql"]
      interval: 10s
      timeout: 10s
      retries: 10

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "4000:80"
    environment:
      - PMA_HOST=mysql:3306
      - PMA_USER=wordpress
      - PMA_PASSWORD=wordpress
      - MYSQL_ROOT_PASSWORD=root 
    depends_on:
      mysql:
        condition: service_healthy

  smtp4dev:
    image: rnwood/smtp4dev:v3
    restart: always
    ports:
      - "5000:80"

volumes:
  mysql-data:
